import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const specs = [
  // ── 1. Toyota Camry 2018-2023 2.5L 4-cyl ─────────────────────────────────
  ...([2018, 2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Toyota",
    model: "Camry",
    trim: "LE/SE",
    engine: "2.5L 4-cyl (A25A-FXS)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "13.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.8,
    oilFilterPN: "Toyota 04152-YZZA6",
    coolantType: "Toyota Super Long Life Coolant (Pink SLLC)",
    coolantCapacityQts: 7.4,
    transType: "8-Speed Automatic (Direct Shift-8AT)",
    transFluidType: "Toyota ATF WS",
    transFluidQts: 3.7,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "35",
    batteryCCA: 560,
    batteryRC: 90,
    tireSizeFront: "205/65R16",
    tireSizeRear: "205/65R16",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 11.1,
    rearRotorDia: 11.1,
    frontRotorMinMM: 25.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 76,
    frontCaliperTorque: 25,
    rearCaliperTorque: 25,
    sparkPlugPN: "NGK ILTR5A-13G",
    sparkPlugGapIn: 0.044,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 17.6,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision System", "Lane Departure Alert", "Automatic High Beams", "Radar Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera adjustment", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 2. Toyota Corolla 2020-2023 2.0L 4-cyl ───────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Toyota",
    model: "Corolla",
    trim: "LE/SE",
    engine: "2.0L 4-cyl (M20A-FKS)",
    engineDisplacement: "2.0L",
    engineCylinders: 4,
    compressionRatio: "13.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.4,
    oilFilterPN: "Toyota 04152-YZZA6",
    coolantType: "Toyota Super Long Life Coolant (Pink SLLC)",
    coolantCapacityQts: 6.2,
    transType: "CVT (Direct Shift-CVT)",
    transFluidType: "Toyota ATF WS",
    transFluidQts: 3.2,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "35",
    batteryCCA: 490,
    batteryRC: 80,
    tireSizeFront: "205/55R16",
    tireSizeRear: "205/55R16",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 10.8,
    rearRotorDia: 10.2,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 76,
    sparkPlugPN: "NGK ILTR5A-13G",
    sparkPlugGapIn: 0.044,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 14.1,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision System", "Lane Departure Alert", "Automatic High Beams", "Radar Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera adjustment"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 3. Toyota RAV4 2019-2023 2.5L 4-cyl ──────────────────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Toyota",
    model: "RAV4",
    trim: "LE/XLE AWD",
    engine: "2.5L 4-cyl (A25A-FKS)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "13.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.8,
    oilFilterPN: "Toyota 04152-YZZA6",
    coolantType: "Toyota Super Long Life Coolant (Pink SLLC)",
    coolantCapacityQts: 7.6,
    transType: "8-Speed Automatic (Direct Shift-8AT)",
    transFluidType: "Toyota ATF WS",
    transFluidQts: 3.7,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Toyota Gear Oil LF 75W",
    diffFluidRearQts: 0.95,
    batteryGroup: "35",
    batteryCCA: 580,
    batteryRC: 90,
    tireSizeFront: "225/65R17",
    tireSizeRear: "225/65R17",
    tirePressureFront: 33,
    tirePressureRear: 33,
    frontRotorDia: 11.6,
    rearRotorDia: 11.1,
    frontRotorMinMM: 25.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 76,
    sparkPlugPN: "NGK ILTR5A-13G",
    sparkPlugGapIn: 0.044,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 17.6,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision System", "Lane Departure Alert", "Automatic High Beams", "Radar Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera adjustment", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 4. Toyota Tacoma 2016-2023 3.5L V6 4x4 ───────────────────────────────
  ...([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Toyota",
    model: "Tacoma",
    trim: "SR5/TRD 4x4",
    engine: "3.5L V6 (2GR-FKS)",
    engineDisplacement: "3.5L",
    engineCylinders: 6,
    compressionRatio: "11.8:1",
    firingOrder: "1-2-3-4-5-6",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 6.2,
    oilFilterPN: "Toyota 04152-YZZA1",
    coolantType: "Toyota Super Long Life Coolant (Pink SLLC)",
    coolantCapacityQts: 10.8,
    transType: "6-Speed Automatic (AC60F)",
    transFluidType: "Toyota ATF WS",
    transFluidQts: 4.0,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "Toyota Gear Oil LF 75W",
    diffFluidFrontQts: 1.5,
    diffFluidRearType: "Toyota Gear Oil LF 75W",
    diffFluidRearQts: 2.4,
    transferCaseFluid: "Toyota ATF WS",
    transferCaseQts: 1.2,
    batteryGroup: "24F",
    batteryCCA: 600,
    batteryRC: 100,
    tireSizeFront: "265/65R17",
    tireSizeRear: "265/65R17",
    tirePressureFront: 32,
    tirePressureRear: 32,
    frontRotorDia: 12.0,
    rearRotorDia: 13.0,
    frontRotorMinMM: 28.0,
    rearRotorMinMM: 16.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 83,
    sparkPlugPN: "NGK ILFR6B11",
    sparkPlugGapIn: 0.043,
    sparkPlugMiles: 60000,
    refrigerantType: "R-134a",
    refrigerantOz: 24.0,
    acOilType: "PAG 46",
    adasFeatures: year >= 2020 ? ["Pre-Collision System", "Lane Departure Alert", "Automatic High Beams"] : [],
    adasCalRequired: year >= 2020 ? ["Windshield replacement", "Front camera adjustment"] : [],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 5. Toyota Highlander 2020-2023 3.5L V6 ───────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Toyota",
    model: "Highlander",
    trim: "LE/XLE AWD",
    engine: "3.5L V6 (2GR-FKS)",
    engineDisplacement: "3.5L",
    engineCylinders: 6,
    compressionRatio: "11.8:1",
    firingOrder: "1-2-3-4-5-6",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 6.4,
    oilFilterPN: "Toyota 04152-YZZA1",
    coolantType: "Toyota Super Long Life Coolant (Pink SLLC)",
    coolantCapacityQts: 11.1,
    transType: "8-Speed Automatic (UA80F)",
    transFluidType: "Toyota ATF WS",
    transFluidQts: 3.7,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Toyota Gear Oil LF 75W",
    diffFluidRearQts: 1.1,
    batteryGroup: "35",
    batteryCCA: 580,
    batteryRC: 90,
    tireSizeFront: "235/65R18",
    tireSizeRear: "235/65R18",
    tirePressureFront: 33,
    tirePressureRear: 33,
    frontRotorDia: 12.0,
    rearRotorDia: 12.0,
    frontRotorMinMM: 27.0,
    rearRotorMinMM: 16.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 76,
    sparkPlugPN: "NGK ILFR6B11",
    sparkPlugGapIn: 0.043,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 19.8,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision System", "Lane Departure Alert", "Automatic High Beams", "Radar Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera adjustment", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 6. Honda Accord 2018-2023 1.5L Turbo ─────────────────────────────────
  ...([2018, 2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Honda",
    model: "Accord",
    trim: "Sport 1.5T",
    engine: "1.5L Turbo 4-cyl (L15BE)",
    engineDisplacement: "1.5L",
    engineCylinders: 4,
    compressionRatio: "10.3:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 3.7,
    oilFilterPN: "Honda 15400-PLM-A02",
    coolantType: "Honda Type 2 Coolant (Blue-Green)",
    coolantCapacityQts: 5.9,
    transType: "CVT (Earth Dreams)",
    transFluidType: "Honda HCF-2",
    transFluidQts: 2.9,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "51R",
    batteryCCA: 410,
    batteryRC: 60,
    tireSizeFront: "235/40R19",
    tireSizeRear: "235/40R19",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 12.0,
    rearRotorDia: 11.1,
    frontRotorMinMM: 28.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 1.6,
    rearPadMinMM: 1.6,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK ILZKBR7B8DG",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 30000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 14.1,
    acOilType: "PAG 46",
    adasFeatures: ["Collision Mitigation Braking", "Lane Keeping Assist", "Adaptive Cruise Control", "Road Departure Mitigation"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 7. Honda Civic 2022-2023 1.5L Turbo ──────────────────────────────────
  ...([2022, 2023] as const).map((year) => ({
    year,
    make: "Honda",
    model: "Civic",
    trim: "Sport/EX",
    engine: "1.5L Turbo 4-cyl (L15CA)",
    engineDisplacement: "1.5L",
    engineCylinders: 4,
    compressionRatio: "10.3:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 3.7,
    oilFilterPN: "Honda 15400-PLM-A02",
    coolantType: "Honda Type 2 Coolant (Blue-Green)",
    coolantCapacityQts: 5.7,
    transType: "CVT (Earth Dreams)",
    transFluidType: "Honda HCF-2",
    transFluidQts: 2.9,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "51R",
    batteryCCA: 410,
    batteryRC: 60,
    tireSizeFront: "215/55R17",
    tireSizeRear: "215/55R17",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 11.1,
    rearRotorDia: 10.2,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 7.0,
    frontPadMinMM: 1.6,
    rearPadMinMM: 1.6,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK ILZKBR7B8DG",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 30000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 12.7,
    acOilType: "PAG 46",
    adasFeatures: ["Collision Mitigation Braking", "Lane Keeping Assist", "Adaptive Cruise Control", "Road Departure Mitigation"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 8. Honda CR-V 2017-2022 1.5L Turbo AWD ───────────────────────────────
  ...([2017, 2018, 2019, 2020, 2021, 2022] as const).map((year) => ({
    year,
    make: "Honda",
    model: "CR-V",
    trim: "EX/EX-L AWD",
    engine: "1.5L Turbo 4-cyl (L15BE)",
    engineDisplacement: "1.5L",
    engineCylinders: 4,
    compressionRatio: "10.3:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 3.7,
    oilFilterPN: "Honda 15400-PLM-A02",
    coolantType: "Honda Type 2 Coolant (Blue-Green)",
    coolantCapacityQts: 5.9,
    transType: "CVT (Earth Dreams)",
    transFluidType: "Honda HCF-2",
    transFluidQts: 2.9,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Honda DPS-F Fluid",
    diffFluidRearQts: 0.85,
    batteryGroup: "51R",
    batteryCCA: 410,
    batteryRC: 60,
    tireSizeFront: "235/60R18",
    tireSizeRear: "235/60R18",
    tirePressureFront: 33,
    tirePressureRear: 33,
    frontRotorDia: 11.8,
    rearRotorDia: 11.1,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 1.6,
    rearPadMinMM: 1.6,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK ILZKBR7B8DG",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 30000,
    refrigerantType: "R-134a",
    refrigerantOz: 14.1,
    acOilType: "PAG 46",
    adasFeatures: ["Collision Mitigation Braking", "Lane Keeping Assist", "Adaptive Cruise Control", "Road Departure Mitigation"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 9. Honda Pilot 2016-2022 3.5L V6 AWD ─────────────────────────────────
  ...([2016, 2017, 2018, 2019, 2020, 2021, 2022] as const).map((year) => ({
    year,
    make: "Honda",
    model: "Pilot",
    trim: "EX-L/Touring AWD",
    engine: "3.5L V6 (J35Y6)",
    engineDisplacement: "3.5L",
    engineCylinders: 6,
    compressionRatio: "11.5:1",
    firingOrder: "1-4-2-5-3-6",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.5,
    oilFilterPN: "Honda 15400-PLM-A02",
    coolantType: "Honda Type 2 Coolant (Blue-Green)",
    coolantCapacityQts: 9.0,
    transType: "9-Speed Automatic (ZF 9HP)",
    transFluidType: "Honda ATF DW-1",
    transFluidQts: 3.8,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Honda DPS-F Fluid",
    diffFluidRearQts: 0.85,
    batteryGroup: "24F",
    batteryCCA: 550,
    batteryRC: 85,
    tireSizeFront: "245/60R18",
    tireSizeRear: "245/60R18",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 12.6,
    rearRotorDia: 12.0,
    frontRotorMinMM: 28.0,
    rearRotorMinMM: 10.0,
    frontPadMinMM: 1.6,
    rearPadMinMM: 1.6,
    wheelNutTorque: 94,
    sparkPlugPN: "NGK IZFR6K11NS",
    sparkPlugGapIn: 0.044,
    sparkPlugMiles: 60000,
    refrigerantType: "R-134a",
    refrigerantOz: 21.0,
    acOilType: "PAG 46",
    adasFeatures: ["Collision Mitigation Braking", "Lane Keeping Assist", "Adaptive Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 10. Ford F-150 2021-2023 5.0L V8 ─────────────────────────────────────
  ...([2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Ford",
    model: "F-150",
    trim: "XLT 5.0L V8",
    engine: "5.0L V8 (Coyote Gen 3)",
    engineDisplacement: "5.0L",
    engineCylinders: 8,
    compressionRatio: "12.0:1",
    firingOrder: "1-5-4-8-6-3-7-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 7.7,
    oilFilterPN: "Motorcraft FL-820-S",
    coolantType: "Ford Motorcraft Orange Prediluted (VC-3DIL-B)",
    coolantCapacityQts: 16.9,
    transType: "10-Speed Automatic (10R80)",
    transFluidType: "Mercon ULV",
    transFluidQts: 6.7,
    brakeFluidType: "DOT 4 LV",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Motorcraft SAE 75W-140 Synthetic",
    diffFluidRearQts: 3.5,
    batteryGroup: "H7 (94R)",
    batteryCCA: 750,
    batteryRC: 130,
    tireSizeFront: "275/65R18",
    tireSizeRear: "275/65R18",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 13.9,
    rearRotorDia: 13.9,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 150,
    sparkPlugPN: "Motorcraft SP-587",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 22.0,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision Assist", "Lane-Keeping System", "Adaptive Cruise Control", "Blind Spot Information System"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 11. Ford F-150 2021-2023 3.5L EcoBoost ───────────────────────────────
  ...([2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Ford",
    model: "F-150",
    trim: "XLT 3.5L EcoBoost",
    engine: "3.5L EcoBoost V6 (Gen 3)",
    engineDisplacement: "3.5L",
    engineCylinders: 6,
    compressionRatio: "10.0:1",
    firingOrder: "1-4-2-5-3-6",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 6.0,
    oilFilterPN: "Motorcraft FL-500-S",
    coolantType: "Ford Motorcraft Orange Prediluted (VC-3DIL-B)",
    coolantCapacityQts: 14.7,
    transType: "10-Speed Automatic (10R80)",
    transFluidType: "Mercon ULV",
    transFluidQts: 6.7,
    brakeFluidType: "DOT 4 LV",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Motorcraft SAE 75W-140 Synthetic",
    diffFluidRearQts: 3.5,
    batteryGroup: "H7 (94R)",
    batteryCCA: 750,
    batteryRC: 130,
    tireSizeFront: "275/65R18",
    tireSizeRear: "275/65R18",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 13.9,
    rearRotorDia: 13.9,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 150,
    sparkPlugPN: "Motorcraft SP-546A",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 22.0,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision Assist", "Lane-Keeping System", "Adaptive Cruise Control", "Blind Spot Information System"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 12. Ford Explorer 2020-2023 2.3L EcoBoost ────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Ford",
    model: "Explorer",
    trim: "XLT/Limited RWD",
    engine: "2.3L EcoBoost 4-cyl",
    engineDisplacement: "2.3L",
    engineCylinders: 4,
    compressionRatio: "9.5:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 5.7,
    oilFilterPN: "Motorcraft FL-910-S",
    coolantType: "Ford Motorcraft Orange Prediluted (VC-3DIL-B)",
    coolantCapacityQts: 12.7,
    transType: "10-Speed Automatic (10R60)",
    transFluidType: "Mercon ULV",
    transFluidQts: 5.3,
    brakeFluidType: "DOT 4 LV",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "H6 (48)",
    batteryCCA: 680,
    batteryRC: 115,
    tireSizeFront: "255/55R20",
    tireSizeRear: "255/55R20",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 12.4,
    rearRotorDia: 12.4,
    frontRotorMinMM: 28.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 150,
    sparkPlugPN: "Motorcraft SP-546A",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 18.0,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision Assist", "Lane-Keeping System", "Adaptive Cruise Control", "Blind Spot Information System"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 13. Ford Escape 2020-2023 1.5L EcoBoost ──────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Ford",
    model: "Escape",
    trim: "SE/SEL FWD",
    engine: "1.5L EcoBoost 3-cyl",
    engineDisplacement: "1.5L",
    engineCylinders: 3,
    compressionRatio: "10.0:1",
    firingOrder: "1-2-3",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 4.7,
    oilFilterPN: "Motorcraft FL-910-S",
    coolantType: "Ford Motorcraft Orange Prediluted (VC-3DIL-B)",
    coolantCapacityQts: 7.8,
    transType: "8-Speed Automatic (8F35)",
    transFluidType: "Mercon LV",
    transFluidQts: 5.7,
    brakeFluidType: "DOT 4 LV",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "H6 (48)",
    batteryCCA: 590,
    batteryRC: 95,
    tireSizeFront: "225/55R19",
    tireSizeRear: "225/55R19",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 12.0,
    rearRotorDia: 11.3,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 100,
    sparkPlugPN: "Motorcraft SP-578",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 14.5,
    acOilType: "PAG 46",
    adasFeatures: ["Pre-Collision Assist", "Lane-Keeping System", "Adaptive Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 14. Chevrolet Silverado 1500 2019-2023 5.3L V8 ───────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT/LTZ 4WD",
    engine: "5.3L V8 (EcoTec3 L84)",
    engineDisplacement: "5.3L",
    engineCylinders: 8,
    compressionRatio: "11.0:1",
    firingOrder: "1-8-7-2-6-5-4-3",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic (Dexos1 Gen 3)",
    oilCapacityQts: 8.0,
    oilFilterPN: "ACDelco PF63E",
    coolantType: "Dex-Cool (Orange)",
    coolantCapacityQts: 14.8,
    transType: "8-Speed Automatic (8L90)",
    transFluidType: "DEXRON-VI ATF",
    transFluidQts: 7.4,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "SAE 75W-90 Synthetic Gear Lubricant",
    diffFluidFrontQts: 1.5,
    diffFluidRearType: "SAE 75W-90 Synthetic Gear Lubricant",
    diffFluidRearQts: 2.7,
    transferCaseFluid: "DEXRON-VI ATF",
    transferCaseQts: 1.8,
    batteryGroup: "H7 (94R)",
    batteryCCA: 720,
    batteryRC: 120,
    tireSizeFront: "275/65R18",
    tireSizeRear: "275/65R18",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 13.6,
    rearRotorDia: 13.6,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 140,
    sparkPlugPN: "ACDelco 41-188",
    sparkPlugGapIn: 0.040,
    sparkPlugMiles: 97500,
    refrigerantType: "R-1234yf",
    refrigerantOz: 22.0,
    acOilType: "PAG 150",
    adasFeatures: ["Forward Collision Alert", "Lane Keep Assist", "Following Distance Indicator", "Automatic Emergency Braking"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 15. Chevrolet Equinox 2018-2023 1.5L Turbo FWD ───────────────────────
  ...([2018, 2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LS/LT FWD",
    engine: "1.5L Turbo 4-cyl (LYX)",
    engineDisplacement: "1.5L",
    engineCylinders: 4,
    compressionRatio: "10.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic (Dexos1)",
    oilCapacityQts: 4.0,
    oilFilterPN: "ACDelco PF63E",
    coolantType: "Dex-Cool (Orange)",
    coolantCapacityQts: 7.8,
    transType: "6-Speed Automatic (6T40)",
    transFluidType: "DEXRON-VI ATF",
    transFluidQts: 7.4,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "48",
    batteryCCA: 590,
    batteryRC: 95,
    tireSizeFront: "225/65R17",
    tireSizeRear: "225/65R17",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 11.6,
    rearRotorDia: 10.9,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 100,
    sparkPlugPN: "ACDelco 41-109",
    sparkPlugGapIn: 0.040,
    sparkPlugMiles: 97500,
    refrigerantType: "R-134a",
    refrigerantOz: 17.6,
    acOilType: "PAG 150",
    adasFeatures: ["Forward Collision Alert", "Lane Keep Assist", "Automatic Emergency Braking"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 16. GMC Sierra 1500 2019-2023 5.3L V8 ────────────────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "GMC",
    model: "Sierra 1500",
    trim: "SLE/SLT 4WD",
    engine: "5.3L V8 (EcoTec3 L84)",
    engineDisplacement: "5.3L",
    engineCylinders: 8,
    compressionRatio: "11.0:1",
    firingOrder: "1-8-7-2-6-5-4-3",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic (Dexos1 Gen 3)",
    oilCapacityQts: 8.0,
    oilFilterPN: "ACDelco PF63E",
    coolantType: "Dex-Cool (Orange)",
    coolantCapacityQts: 14.8,
    transType: "8-Speed Automatic (8L90)",
    transFluidType: "DEXRON-VI ATF",
    transFluidQts: 7.4,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "SAE 75W-90 Synthetic Gear Lubricant",
    diffFluidFrontQts: 1.5,
    diffFluidRearType: "SAE 75W-90 Synthetic Gear Lubricant",
    diffFluidRearQts: 2.7,
    transferCaseFluid: "DEXRON-VI ATF",
    transferCaseQts: 1.8,
    batteryGroup: "H7 (94R)",
    batteryCCA: 720,
    batteryRC: 120,
    tireSizeFront: "275/65R18",
    tireSizeRear: "275/65R18",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 13.6,
    rearRotorDia: 13.6,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 140,
    sparkPlugPN: "ACDelco 41-188",
    sparkPlugGapIn: 0.040,
    sparkPlugMiles: 97500,
    refrigerantType: "R-1234yf",
    refrigerantOz: 22.0,
    acOilType: "PAG 150",
    adasFeatures: ["Forward Collision Alert", "Lane Keep Assist", "Following Distance Indicator", "Automatic Emergency Braking"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 17. Dodge Ram 1500 2019-2023 5.7L HEMI 4x4 ───────────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Ram",
    model: "1500",
    trim: "Big Horn/Laramie 4x4",
    engine: "5.7L HEMI V8 (Eagle)",
    engineDisplacement: "5.7L",
    engineCylinders: 8,
    compressionRatio: "10.9:1",
    firingOrder: "1-8-4-3-6-5-7-2",
    timingType: "chain",
    oilType: "5W-20 Full Synthetic (Mopar)",
    oilCapacityQts: 7.0,
    oilFilterPN: "Mopar 68191349AC",
    coolantType: "Mopar OAT (Orange/Red - HOAT)",
    coolantCapacityQts: 16.7,
    transType: "8-Speed Automatic (ZF 8HP75)",
    transFluidType: "Mopar ATF+4",
    transFluidQts: 8.0,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "Mopar Power Steering Fluid",
    diffFluidFrontType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidFrontQts: 1.3,
    diffFluidRearType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidRearQts: 3.5,
    transferCaseFluid: "Mopar Transfer Case Fluid",
    transferCaseQts: 1.1,
    batteryGroup: "H7 (94R)",
    batteryCCA: 730,
    batteryRC: 125,
    tireSizeFront: "275/55R20",
    tireSizeRear: "275/55R20",
    tirePressureFront: 36,
    tirePressureRear: 36,
    frontRotorDia: 13.9,
    rearRotorDia: 13.8,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 22.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 130,
    sparkPlugPN: "NGK 4363",
    sparkPlugGapIn: 0.042,
    sparkPlugMiles: 30000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 24.0,
    acOilType: "PAG 100",
    adasFeatures: ["Forward Collision Warning", "Lane Departure Warning", "Adaptive Cruise Control", "Blind Spot Monitoring"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 18. Jeep Grand Cherokee 2021-2023 3.6L V6 ────────────────────────────
  ...([2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Laredo/Limited 4WD",
    engine: "3.6L Pentastar V6 (ERB)",
    engineDisplacement: "3.6L",
    engineCylinders: 6,
    compressionRatio: "11.3:1",
    firingOrder: "1-2-3-4-5-6",
    timingType: "chain",
    oilType: "5W-20 Full Synthetic (Mopar)",
    oilCapacityQts: 5.9,
    oilFilterPN: "Mopar 68191349AC",
    coolantType: "Mopar OAT (Orange/Red - HOAT)",
    coolantCapacityQts: 12.0,
    transType: "8-Speed Automatic (ZF 8HP75)",
    transFluidType: "Mopar ATF+4",
    transFluidQts: 8.0,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidFrontQts: 1.3,
    diffFluidRearType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidRearQts: 1.9,
    transferCaseFluid: "Mopar Transfer Case Fluid",
    transferCaseQts: 1.0,
    batteryGroup: "H6 (48)",
    batteryCCA: 650,
    batteryRC: 110,
    tireSizeFront: "265/50R20",
    tireSizeRear: "265/50R20",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 13.6,
    rearRotorDia: 13.0,
    frontRotorMinMM: 32.0,
    rearRotorMinMM: 20.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 130,
    sparkPlugPN: "NGK 4363",
    sparkPlugGapIn: 0.042,
    sparkPlugMiles: 30000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 21.0,
    acOilType: "PAG 100",
    adasFeatures: ["Forward Collision Warning", "Lane Departure Warning", "Adaptive Cruise Control", "Blind Spot Monitoring", "Rear Cross Path Detection"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Rear camera replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 19. Jeep Wrangler 2018-2023 3.6L V6 4-Door ───────────────────────────
  ...([2018, 2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Jeep",
    model: "Wrangler",
    trim: "Sport/Sahara 4-Door (JL)",
    engine: "3.6L Pentastar V6 (ERB)",
    engineDisplacement: "3.6L",
    engineCylinders: 6,
    compressionRatio: "11.3:1",
    firingOrder: "1-2-3-4-5-6",
    timingType: "chain",
    oilType: "5W-20 Full Synthetic (Mopar)",
    oilCapacityQts: 5.9,
    oilFilterPN: "Mopar 68191349AC",
    coolantType: "Mopar OAT (Orange/Red - HOAT)",
    coolantCapacityQts: 12.6,
    transType: "8-Speed Automatic (ZF 8HP50)",
    transFluidType: "Mopar ATF+4",
    transFluidQts: 7.4,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidFrontQts: 1.1,
    diffFluidRearType: "Mopar 75W-90 Synthetic Gear & Axle Lubricant",
    diffFluidRearQts: 1.1,
    transferCaseFluid: "Mopar Transfer Case Fluid",
    transferCaseQts: 1.0,
    batteryGroup: "H6 (48)",
    batteryCCA: 650,
    batteryRC: 110,
    tireSizeFront: "255/75R17",
    tireSizeRear: "255/75R17",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 12.9,
    rearRotorDia: 12.9,
    frontRotorMinMM: 27.0,
    rearRotorMinMM: 15.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 130,
    sparkPlugPN: "NGK 4363",
    sparkPlugGapIn: 0.042,
    sparkPlugMiles: 30000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 18.0,
    acOilType: "PAG 100",
    adasFeatures: ["Forward Collision Warning", "Blind Spot Monitoring", "Rear Cross Path Detection"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 20. Nissan Altima 2019-2023 2.5L ─────────────────────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Nissan",
    model: "Altima",
    trim: "S/SV FWD",
    engine: "2.5L 4-cyl (QR25DE)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "9.8:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.9,
    oilFilterPN: "Nissan 15208-65F00",
    coolantType: "Nissan L248SP (Blue-Green Long Life)",
    coolantCapacityQts: 7.4,
    transType: "CVT (Xtronic)",
    transFluidType: "Nissan CVT Fluid NS-3",
    transFluidQts: 6.8,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "35",
    batteryCCA: 550,
    batteryRC: 85,
    tireSizeFront: "235/40R19",
    tireSizeRear: "235/40R19",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 11.7,
    rearRotorDia: 11.5,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK DILKAR6A11H",
    sparkPlugGapIn: 0.043,
    sparkPlugMiles: 105000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 14.8,
    acOilType: "PAG 46",
    adasFeatures: ["Automatic Emergency Braking", "Blind Spot Warning", "Rear Cross Traffic Alert", "Lane Departure Warning"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 21. Nissan Rogue 2021-2023 1.5L Turbo AWD ────────────────────────────
  ...([2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Nissan",
    model: "Rogue",
    trim: "S/SV AWD",
    engine: "1.5L Turbo 3-cyl (KR15DDT)",
    engineDisplacement: "1.5L",
    engineCylinders: 3,
    compressionRatio: "10.7:1",
    firingOrder: "1-2-3",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 4.4,
    oilFilterPN: "Nissan 15208-65F00",
    coolantType: "Nissan L248SP (Blue-Green Long Life)",
    coolantCapacityQts: 7.2,
    transType: "CVT (Xtronic)",
    transFluidType: "Nissan CVT Fluid NS-3",
    transFluidQts: 6.2,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "Nissan 75W-90 Gear Oil",
    diffFluidRearQts: 0.8,
    batteryGroup: "35",
    batteryCCA: 550,
    batteryRC: 85,
    tireSizeFront: "225/65R17",
    tireSizeRear: "225/65R17",
    tirePressureFront: 35,
    tirePressureRear: 35,
    frontRotorDia: 12.6,
    rearRotorDia: 12.0,
    frontRotorMinMM: 26.0,
    rearRotorMinMM: 10.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK DILKAR6A11H",
    sparkPlugGapIn: 0.043,
    sparkPlugMiles: 105000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 15.9,
    acOilType: "PAG 46",
    adasFeatures: ["Automatic Emergency Braking", "Blind Spot Warning", "Rear Cross Traffic Alert", "Lane Departure Warning", "ProPilot Assist"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 22. Hyundai Sonata 2020-2023 2.5L ────────────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Hyundai",
    model: "Sonata",
    trim: "SE/SEL FWD",
    engine: "2.5L 4-cyl (Smartstream G2.5 GDI)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "13.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 5.1,
    oilFilterPN: "Hyundai 26300-35503",
    coolantType: "Hyundai HOAT (Blue)",
    coolantCapacityQts: 7.4,
    transType: "8-Speed Automatic (8AT)",
    transFluidType: "Hyundai/Kia SP-IV-M ATF",
    transFluidQts: 5.8,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "H6 (48)",
    batteryCCA: 600,
    batteryRC: 100,
    tireSizeFront: "235/45R18",
    tireSizeRear: "235/45R18",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 12.6,
    rearRotorDia: 11.5,
    frontRotorMinMM: 26.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK ILKR7E-9",
    sparkPlugGapIn: 0.039,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 16.9,
    acOilType: "PAG 46",
    adasFeatures: ["Forward Collision-Avoidance Assist", "Lane Keeping Assist", "Driver Attention Warning", "Smart Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 23. Hyundai Tucson 2022-2023 2.5L AWD ────────────────────────────────
  ...([2022, 2023] as const).map((year) => ({
    year,
    make: "Hyundai",
    model: "Tucson",
    trim: "SE/SEL AWD",
    engine: "2.5L 4-cyl (Smartstream G2.5 GDI)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "13.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic",
    oilCapacityQts: 5.1,
    oilFilterPN: "Hyundai 26300-35503",
    coolantType: "Hyundai HOAT (Blue)",
    coolantCapacityQts: 7.2,
    transType: "8-Speed Automatic (8AT) with AWD",
    transFluidType: "Hyundai/Kia SP-IV-M ATF",
    transFluidQts: 5.8,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidRearType: "SAE 75W-90 Synthetic",
    diffFluidRearQts: 0.85,
    batteryGroup: "H6 (48)",
    batteryCCA: 600,
    batteryRC: 100,
    tireSizeFront: "235/55R18",
    tireSizeRear: "235/55R18",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 12.6,
    rearRotorDia: 11.5,
    frontRotorMinMM: 26.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 80,
    sparkPlugPN: "NGK ILKR7E-9",
    sparkPlugGapIn: 0.039,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 17.6,
    acOilType: "PAG 46",
    adasFeatures: ["Forward Collision-Avoidance Assist", "Lane Keeping Assist", "Blind-Spot Collision Warning", "Smart Cruise Control"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 24. Subaru Outback 2020-2023 2.5L CVT ────────────────────────────────
  ...([2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "Subaru",
    model: "Outback",
    trim: "Base/Premium AWD",
    engine: "2.5L Boxer 4-cyl (FB25D)",
    engineDisplacement: "2.5L",
    engineCylinders: 4,
    compressionRatio: "10.4:1",
    firingOrder: "1-3-2-4",
    timingType: "chain",
    oilType: "0W-20 Full Synthetic",
    oilCapacityQts: 5.1,
    oilFilterPN: "Subaru 15208AA170",
    coolantType: "Subaru Super Coolant (Blue-Green)",
    coolantCapacityQts: 7.5,
    transType: "CVT (Lineartronic)",
    transFluidType: "Subaru CVTF-II",
    transFluidQts: 7.4,
    brakeFluidType: "DOT 3",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    diffFluidFrontType: "Subaru Gear Oil 75W-90",
    diffFluidFrontQts: 0.8,
    diffFluidRearType: "Subaru Gear Oil 75W-90",
    diffFluidRearQts: 0.8,
    batteryGroup: "25",
    batteryCCA: 550,
    batteryRC: 85,
    tireSizeFront: "225/60R18",
    tireSizeRear: "225/60R18",
    tirePressureFront: 35,
    tirePressureRear: 33,
    frontRotorDia: 11.6,
    rearRotorDia: 11.4,
    frontRotorMinMM: 24.0,
    rearRotorMinMM: 8.0,
    frontPadMinMM: 2.0,
    rearPadMinMM: 2.0,
    wheelNutTorque: 89,
    sparkPlugPN: "NGK ILZKBR7B8DG",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 60000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 17.6,
    acOilType: "PAG 46",
    adasFeatures: ["EyeSight Pre-Collision Braking", "Adaptive Cruise Control", "Lane Keep Assist", "Lane Departure Warning"],
    adasCalRequired: ["Windshield replacement", "EyeSight stereo camera calibration (both cameras)"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),

  // ── 25. BMW 3 Series 2019-2023 330i 2.0L Turbo ───────────────────────────
  ...([2019, 2020, 2021, 2022, 2023] as const).map((year) => ({
    year,
    make: "BMW",
    model: "3 Series",
    trim: "330i (G20)",
    engine: "2.0L Turbo 4-cyl (B48B20B)",
    engineDisplacement: "2.0L",
    engineCylinders: 4,
    compressionRatio: "11.0:1",
    firingOrder: "1-3-4-2",
    timingType: "chain",
    oilType: "5W-30 Full Synthetic (BMW LL-01 / LL-04)",
    oilCapacityQts: 5.3,
    oilFilterPN: "BMW 11427953125",
    coolantType: "BMW Blue Coolant (HT12 HOAT)",
    coolantCapacityQts: 8.5,
    transType: "8-Speed Automatic (ZF 8HP45)",
    transFluidType: "ZF Lifeguard Fluid 8",
    transFluidQts: 6.4,
    brakeFluidType: "DOT 4 (BMW spec)",
    powerSteeringFluid: "EPS (Electric - No Fluid)",
    batteryGroup: "H7 (94R) AGM",
    batteryCCA: 800,
    batteryRC: 140,
    tireSizeFront: "225/50R17",
    tireSizeRear: "255/40R17",
    tirePressureFront: 35,
    tirePressureRear: 38,
    frontRotorDia: 12.4,
    rearRotorDia: 11.8,
    frontRotorMinMM: 22.4,
    rearRotorMinMM: 9.0,
    frontPadMinMM: 3.0,
    rearPadMinMM: 3.0,
    wheelNutTorque: 103,
    frontCaliperTorque: 26,
    rearCaliperTorque: 26,
    sparkPlugPN: "NGK ILZKAR8J8SY",
    sparkPlugGapIn: 0.028,
    sparkPlugMiles: 45000,
    refrigerantType: "R-1234yf",
    refrigerantOz: 16.9,
    acOilType: "PAG 46",
    adasFeatures: ["Automatic Emergency Braking", "Lane Departure Warning", "Blind Spot Detection", "Active Cruise Control with Stop & Go"],
    adasCalRequired: ["Windshield replacement", "Front camera calibration", "Front radar replacement", "Rear radar replacement (BSD)"],
    obd2Protocol: "CAN (ISO 15765-4)",
    evapSystemType: "Enhanced EVAP",
  })),
];

export async function seedSpecs() {
  console.log(`Seeding ${specs.length} vehicle spec records...`);
  let upserted = 0;
  let errors = 0;

  for (const spec of specs) {
    try {
      await prisma.vehicleSpec.upsert({
        where: {
          year_make_model_trim_engine: {
            year: spec.year,
            make: spec.make,
            model: spec.model,
            trim: spec.trim ?? null,
            engine: spec.engine ?? null,
          },
        },
        update: spec,
        create: spec,
      });
      upserted++;
    } catch (err) {
      console.error(`Failed to upsert ${spec.year} ${spec.make} ${spec.model} ${spec.trim}:`, err);
      errors++;
    }
  }

  console.log(`Done. Upserted: ${upserted}, Errors: ${errors}`);
}

// Run directly: npx ts-node --project tsconfig.json prisma/seed-specs.ts
if (require.main === module) {
  seedSpecs()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
